import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import planeahead from './tools/eslint/index.js';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.turbo/**',
      '**/.wrangler/**',
      // Generated by `wrangler types` and committed. 15k lines of runtime declarations with their
      // own eslint-disable directives; linting it reports on Cloudflare's code, not ours.
      'apps/api/worker-configuration.d.ts',
      // apps/mobile: continuous native generation output, Expo's generated types, `expo export`
      // output, and drizzle-kit's generated migrations (never edited by hand; a CI guard holds
      // them byte for byte, scripts/mobile-migrations-guard.mjs).
      'apps/mobile/ios/**',
      'apps/mobile/android/**',
      'apps/mobile/.expo/**',
      'apps/mobile/dist/**',
      'apps/mobile/src/lib/db/migrations/**',
      // The typed client's consumer check (increment 8): it imports the declaration `tsc -b`
      // emits into dist/, which lint cannot assume exists; the api `typecheck` script checks it.
      'apps/api/test/consumer/**',
    ],
  },
  js.configs.recommended,
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: globals.node,
    },
  },
  {
    files: ['packages/*/**/*.ts', 'apps/api/**/*.ts'],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: globals.node,
    },
  },
  {
    // The Expo app (increment 9): typed linting against apps/mobile/tsconfig.json (Expo's base,
    // `react-native` resolution condition), the two classic hooks rules, and the globals Jest and
    // React Native provide. Its Babel, Metro and Jest configs are CommonJS because those tools
    // load them with require().
    files: ['apps/mobile/**/*.ts', 'apps/mobile/**/*.tsx'],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.jest, __DEV__: 'readonly' },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
    },
  },
  {
    files: ['apps/mobile/*.js'],
    languageOptions: { sourceType: 'commonjs', globals: globals.node },
  },
  {
    // Every file ESLint sees, source and test alike. A raw NUL anywhere makes git treat that blob
    // as binary, and the file loses its diff for good; catching it here is what makes the failure
    // loud, because prettier, tsc and the toolchain guard all accept it silently.
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.mjs', '**/*.cjs'],
    plugins: { planeahead },
    rules: {
      'planeahead/no-literal-control-characters': 'error',
    },
  },
  {
    files: ['apps/api/src/**/*.ts', 'packages/db/src/**/*.ts'],
    plugins: { planeahead },
    rules: {
      'planeahead/no-module-scope-drizzle': 'error',
    },
  },
  prettier,
);
