import { describe, expect, it } from 'vitest';
import * as shared from '../src/index';
import { PLANEAHEAD } from '../src/index';

/**
 * The public surface. Removing or renaming an export is a breaking change for apps/api and
 * apps/mobile, so the list is explicit: adding an export means adding it here. This pins the
 * value exports; `types.test.ts` pins the type exports the same way at typecheck time.
 */
const EXPECTED_EXPORTS = [
  // index
  'PLANEAHEAD',
  // adb-time
  'parseAdbDateTime',
  // airports
  'AirportRefSchema',
  'IATA_AIRPORT_RE',
  'ICAO_AIRPORT_RE',
  'SYNTHETIC_ICAO_RE',
  'isSyntheticIcao',
  'isValidTimeZone',
  // cadence
  'A1_EXPECTED_POLLS',
  'A2_ALERT_EVENTS',
  'A2_EXPECTED_ALERTS',
  'A2_EXPECTED_PE',
  'A2_EXPECTED_POLLS',
  'A2_HARD_CAP_PE',
  'A2_SOFT_CAP_PE',
  'ASSUMED_ALERTS_PER_FLIGHT',
  'ASSUMED_B_ADB_ALERT_ITEMS_PER_FLIGHT',
  'ASSUMED_B_AEROAPI_ALERTS_PER_FLIGHT',
  'B_ALERT_EVENTS',
  'B_EXPECTED_POLLS',
  'CADENCES',
  'CADENCE_A1',
  'CADENCE_A2',
  'CADENCE_B',
  'CADENCE_LITERAL',
  'CadenceError',
  'DAY_MS',
  'DEFAULT_CADENCE_PARAMS',
  'LIFETIME_AFTER_SCHEDULED_IN_MINUTES',
  'LITERAL_EXPECTED_POLLS',
  'MAX_LIFETIME',
  'MINUTE_MS',
  'PRE_48H_RELAXATION_REASON',
  'PRE_48H_WINDOWS',
  'SLO_EVENTS',
  'SLO_REPORT_LEAD_TIME_DAYS',
  'SLO_TABLE',
  'SLO_WINDOWS',
  'SLO_WINDOW_BOUNDS',
  'days',
  'expectedCalls',
  'gapAcross',
  'hours',
  'isIntervalWindow',
  'maxLifetime',
  'nextSlot',
  'pollGaps',
  'refreshIntervalFor',
  'resolveWindows',
  'sloRelaxations',
  'slotCount',
  'strictestPollSlo',
  'windowAt',
  // carriers
  'CARRIER_IATA_TO_ICAO_FALLBACK',
  'CarrierRefSchema',
  'IATA_CARRIER_RE',
  'ICAO_CARRIER_RE',
  'carrierIcaoFromIata',
  'resolveCarrierIcao',
  // cost
  'ADB_UNITS',
  'ADB_UNIT_PRICE_USD_MICROS',
  'AERODATABOX_OPERATIONS',
  'AEROAPI_OPERATIONS',
  'AEROAPI_STANDARD_MONTHLY_MINIMUM_USD_MICROS',
  'AEROAPI_STATUS_PRICE_USD_MICROS',
  'LIST_PRICE_USD_MICROS',
  'UnknownOperationError',
  'costUnits',
  'estimateCostUsdMicros',
  'listPriceUsdMicros',
  'pollEquivalents',
  // flight-key
  'FLIGHT_KEY_RE',
  'FlightKeyError',
  'FlightKeySchema',
  'REGIONAL_OPERATOR_CONFIDENCES',
  'REGIONAL_OPERATOR_SEED',
  'RegionalOperatorRuleSchema',
  'RegionalOperatorSeedSchema',
  'buildFlightKey',
  'canonicalizeFromProvider',
  'classifyKeyDrift',
  'flightNumberToken',
  'isFlightKey',
  'isValidIsoDate',
  'normalizeFlightNumber',
  'originLocalDate',
  'parseDesignator',
  'parseFlightKey',
  'reconcileFlightKey',
  'regionalOperatorHint',
  'scheduledDepartureDateLocalOf',
  // flight-status
  'AEROAPI_EVENT_CODES',
  'ALERT_EVENTS',
  'AeroApiEventCodeSchema',
  'OPERATOR_SOURCES',
  'OperatorSourceSchema',
  'aeroApiEventKind',
  'AircraftPositionSchema',
  'AlertEventSchema',
  'BoardRowSchema',
  'CodeshareSchema',
  'FIELD_QUALITY_VALUES',
  'FLIGHT_NUMBER_RE',
  'FLIGHT_STATUS_VALUES',
  'FieldQualityKeySchema',
  'FieldQualitySchema',
  'FlightRefSchema',
  'FlightStatusSchema',
  'FlightStatusValueSchema',
  'FlightTimesSchema',
  'ICAO_HEX_RE',
  'normalizeIcaoHex',
  'IsoDateSchema',
  'IsoInstantSchema',
  'PROVIDER_CALL_RESULTS',
  'PROVIDER_CALL_TRIGGERS',
  'PROVIDER_EVENT_KINDS',
  'PROVIDER_IDS',
  'ProviderCallRecordSchema',
  'ProviderCallResultSchema',
  'ProviderCallTriggerSchema',
  'ProviderEventKindSchema',
  'ProviderEventSchema',
  'ProviderIdSchema',
  'ProviderRefSchema',
  'TIME_FIELDS',
  'tolerantEnum',
  // ids
  'MissingCryptoError',
  'UUID_V7_RE',
  'createUuidv7Generator',
  'isUuidv7',
  'uuidv7',
  'uuidv7Timestamp',
  // live-activity
  'LIVE_ACTIVITY_FIELD_MAX_LENGTH',
  'LIVE_ACTIVITY_PAYLOAD_LIMIT_BYTES',
  'LiveActivityContentStateV1',
  // operator
  'CODESHARE_STATUSES',
  'CodeshareStatusSchema',
  'callsignOperator',
  'parseAirlineCallsign',
  'resolveOperator',
  // outbox
  'DEAD_LETTER_RESEND_MAX_MS',
  'DEAD_LETTER_RESEND_MS',
  'DESIGNATOR_RESOLVER_ORIGIN_PREFIX',
  'FLIGHT_TRACKER_ORIGIN_PREFIX',
  'FLIGHT_TRACKING_STATES',
  'FlightEventMessageV1',
  'FlightEventOutboxPayloadV1',
  'FlightInstanceMessageV1',
  'FlightInstanceOutboxPayloadV1',
  'FlightTrackingStateSchema',
  'OUTBOX_KINDS',
  'OUTBOX_SCHEMA_VERSION',
  'PersistMessageIdentityV1',
  'PersistMessageV1',
  'ProviderBudgetDailyMessageV1',
  'ProviderBudgetDailyPayloadV1',
  'ProviderBudgetKillSwitchMessageV1',
  'ProviderBudgetKillSwitchPayloadV1',
  'ProviderCallMessageV1',
  'ReconcileMessageV1',
  'RefreshCadenceSchema',
  'deadLetterResendSpacingMs',
  'designatorResolverOrigin',
  'flightTrackerOrigin',
  'parseFlightTrackerOrigin',
  // preferences
  'DEFAULT_USER_PREFERENCES',
  'DISTANCE_UNITS',
  'DistanceUnitSchema',
  'PREFERENCE_SETTINGS_KEY_RE',
  'PREFERENCE_SETTINGS_MAX_KEYS',
  'PreferenceSettingsSchema',
  'TEMPERATURE_UNITS',
  'TIME_FORMATS',
  'TemperatureUnitSchema',
  'TimeFormatSchema',
  'UserPreferencesPatchSchema',
  'UserPreferencesSchema',
  // provider-call-point
  'PROVIDER_CALL_POINT_BLOBS',
  'PROVIDER_CALL_POINT_DOUBLES',
  'providerCallPoint',
  // rpc
  'ConfirmPersistedRequestV1',
  'ConfirmPersistedResponseV1',
  'ForceRefreshRequestV1',
  'ForceRefreshResponseV1',
  'GetCostLedgerResponseV1',
  'GetStateResponseV1',
  'HealthResponseV1',
  'INFLIGHT_STALE_MS',
  'IngestProviderEventResponseV1',
  'ListSubscribersRequestV1',
  'ListSubscribersResponseV1',
  'NotificationOverridesSchema',
  'ProviderEventV1',
  'RPC_SCHEMA_VERSION',
  'ResolveRequestV1',
  'ResolveResponseV1',
  'RpcRequestError',
  'SeedRequestV1',
  'SeedResponseV1',
  'SubscribeRequestV1',
  'SubscribeResponseV1',
  'TRACKER_HEALTH_PHASES',
  'TRACKER_PHASES',
  'TrackerHealthPhaseSchema',
  'TrackerPhaseSchema',
  'TrackerSubscriberV1',
  'USER_REFRESH_FRESHNESS_MS',
  'UnsubscribeRequestV1',
  'UnsubscribeResponseV1',
  'parseRpcRequest',
  // secrets
  'SECRET_PATTERNS',
  'findSecretPatterns',
  // status-derivation
  'ADB_STATUSES',
  'AdbStatusSchema',
  'adbFlags',
  'deriveStatus',
  'disambiguateRevisedTime',
  'isActualAt',
  // sync (increment 8)
  'FlightSubscriptionRowV1',
  'SYNC_CURSOR_MAX_LENGTH',
  'SYNC_ENTITIES',
  'SYNC_ENVELOPE_VERSION',
  'SYNC_OPS',
  'SyncChangeV1',
  'SyncCursorError',
  'SyncCursorWireSchema',
  'SyncEntitySchema',
  'SyncEnvelopeV1',
  'SyncFlightV1',
  'SyncOpSchema',
  'decodeSyncCursor',
  'encodeSyncCursor',
  // api (increment 8)
  'DEPLOYMENT_ENVIRONMENTS',
  'DesignatorInputSchema',
  'FlightSearchSuggestionSchema',
  'OriginAirportInputSchema',
  'SUBSCRIPTION_CABINS',
  'SubscribeFlightBodySchema',
  'SubscriptionPrefsSchema',
  // errors (increment 8)
  'API_ERROR_CODES',
  'ApiErrorCodeSchema',
  'ApiErrorSchema',
  'ValidationIssueSchema',
  'isApiError',
  // events (increment 12)
  'PRODUCT_EVENTS_MAX_BATCH',
  'PRODUCT_EVENTS_MAX_BODY_BYTES',
  'PRODUCT_EVENT_NAMES',
  'PRODUCT_EVENT_POINT_BLOBS',
  'PRODUCT_EVENT_PROPS_MAX_BYTES',
  'PRODUCT_EVENT_PROPS_MAX_KEYS',
  'PRODUCT_EVENT_PROP_VALUE_MAX_LENGTH',
  'ProductEventNameSchema',
  'ProductEventPropsSchema',
  'ProductEventV1',
  'ProductEventsAcceptedV1',
  'ProductEventsBatchV1',
  'productEventPoint',
  // limits (increment 8)
  'CAP_NAMES',
  'DELETED_SESSION_RETENTION_DAYS',
  'DELETED_SUBJECT_RETENTION_DAYS',
  'DO_CALL_DEADLINE_MS',
  'FREE_TIER_LIMITS',
  'IDEMPOTENCY_TTL_SECONDS',
  'LIVE_TRACKING_LEAD_MS',
  'SYNC_PAGE_SIZE',
  'SYNC_RETENTION_DAYS',
  'freeTierLimit',
  'isInLiveWindow',
].sort();

describe('@planeahead/shared', () => {
  it('exports the project name constant', () => {
    expect(PLANEAHEAD).toBe('planeahead');
  });

  it('has no default export', () => {
    expect('default' in shared).toBe(false);
  });

  it('exports exactly the documented public surface', () => {
    expect(Object.keys(shared).sort()).toEqual(EXPECTED_EXPORTS);
  });
});
