-- Generated by drizzle-kit generate --name sync_feed_and_deletion (increment 8, rulings K2, K4,
-- K8 and K13; every spec sentence that says "migration 0002" means this file). The flight half of
-- the sync feed (flight_sync_changes with its (flight_instance_id, xid, seq) index), the change
-- row's own payload (user_sync_changes.row), one deleted_subjects row per deleted identifier
-- (provider_subject_hash, expires_at; subject_id is no longer unique), the per-subscription
-- live_tracked flag the unsubscribe releases its counter slot by, and the increment 8 counter
-- names in usage_counters_counter_check. No existing column changes type or nullability; no
-- table here carries a STORED generated column, so no set_updated_at trigger is recreated.
CREATE TABLE "flight_sync_changes" (
	"seq" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "flight_sync_changes_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"flight_instance_id" uuid NOT NULL,
	"xid" "xid8" DEFAULT pg_current_xact_id() NOT NULL,
	"snapshot" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "usage_counters" DROP CONSTRAINT "usage_counters_counter_check";--> statement-breakpoint
DROP INDEX "deleted_subjects_subject_id_key";--> statement-breakpoint
ALTER TABLE "deleted_subjects" ADD COLUMN "provider_subject_hash" text;--> statement-breakpoint
ALTER TABLE "deleted_subjects" ADD COLUMN "expires_at" timestamp with time zone DEFAULT now() + interval '400 days' NOT NULL;--> statement-breakpoint
ALTER TABLE "user_sync_changes" ADD COLUMN "row" jsonb;--> statement-breakpoint
ALTER TABLE "flight_subscriptions" ADD COLUMN "live_tracked" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "flight_sync_changes" ADD CONSTRAINT "flight_sync_changes_flight_instance_id_flight_instances_id_fk" FOREIGN KEY ("flight_instance_id") REFERENCES "public"."flight_instances"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "flight_sync_changes_flight_instance_id_xid_seq_idx" ON "flight_sync_changes" USING btree ("flight_instance_id","xid","seq");--> statement-breakpoint
CREATE INDEX "deleted_subjects_subject_id_idx" ON "deleted_subjects" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "deleted_subjects_provider_subject_hash_idx" ON "deleted_subjects" USING btree ("provider_subject_hash") WHERE "deleted_subjects"."provider_subject_hash" is not null;--> statement-breakpoint
CREATE INDEX "deleted_subjects_expires_at_idx" ON "deleted_subjects" USING btree ("expires_at");--> statement-breakpoint
ALTER TABLE "deleted_subjects" ADD CONSTRAINT "deleted_subjects_provider_subject_hash_check" CHECK ("deleted_subjects"."provider_subject_hash" is null or "deleted_subjects"."provider_subject_hash" ~ '^(apple|google|session):[A-Za-z0-9_-]{43}$');--> statement-breakpoint
ALTER TABLE "usage_counters" ADD CONSTRAINT "usage_counters_counter_check" CHECK ("usage_counters"."counter" in ('active_subscriptions', 'instances_created', 'magic_links', 'refreshes', 'anonymous_creations', 'imports', 'exports', 'mcp_calls', 'share_links', 'live_tracked', 'tracker_creations') or "usage_counters"."counter" ~ '^refresh:[A-Z0-9-]{10,40}$');