-- Generated by drizzle-kit generate --name sync_feed_and_deletion (increment 8, rulings K2, K4,
-- K8 and K13; every spec sentence that says "migration 0002" means this file). The flight half of
-- the sync feed (flight_sync_changes with its (flight_instance_id, xid, seq) index), the change
-- row's own payload (user_sync_changes.row), one deleted_subjects row per deleted identifier
-- (provider_subject_hash, expires_at; subject_id is no longer unique), the per-subscription
-- live_tracked flag the unsubscribe releases its counter slot by, and the increment 8 counter
-- names in usage_counters_counter_check. No existing column changes type or nullability; no
-- table here carries a STORED generated column, so no set_updated_at trigger is recreated.
-- The review round (rulings O3, O9 and O12), folded in here because no deployment has applied
-- this migration yet: flight_sync_changes.seq draws from user_sync_changes' own identity sequence
-- (the persist consumer now writes both tables in one transaction, and a shared sequence keeps
-- an (xid, seq) pair naming one row across them), and the two one-row tables of the sync
-- contract, sync_epoch (the database timeline every cursor names, seeded 1 below and bumped by
-- the restore runbook) and sync_horizon (the purge horizon H, null until the increment 12 purge
-- writes it), generated by drizzle-kit and appended with their seed rows.
CREATE TABLE "flight_sync_changes" (
	"seq" bigint PRIMARY KEY DEFAULT nextval('user_sync_changes_seq_seq'::regclass) NOT NULL,
	"flight_instance_id" uuid NOT NULL,
	"xid" "xid8" DEFAULT pg_current_xact_id() NOT NULL,
	"snapshot" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "usage_counters" DROP CONSTRAINT "usage_counters_counter_check";--> statement-breakpoint
DROP INDEX "deleted_subjects_subject_id_key";--> statement-breakpoint
ALTER TABLE "deleted_subjects" ADD COLUMN "provider_subject_hash" text;--> statement-breakpoint
ALTER TABLE "deleted_subjects" ADD COLUMN "expires_at" timestamp with time zone DEFAULT now() + interval '400 days' NOT NULL;--> statement-breakpoint
ALTER TABLE "user_sync_changes" ADD COLUMN "row" jsonb;--> statement-breakpoint
ALTER TABLE "flight_subscriptions" ADD COLUMN "live_tracked" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "flight_sync_changes" ADD CONSTRAINT "flight_sync_changes_flight_instance_id_flight_instances_id_fk" FOREIGN KEY ("flight_instance_id") REFERENCES "public"."flight_instances"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "flight_sync_changes_flight_instance_id_xid_seq_idx" ON "flight_sync_changes" USING btree ("flight_instance_id","xid","seq");--> statement-breakpoint
CREATE INDEX "deleted_subjects_subject_id_idx" ON "deleted_subjects" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "deleted_subjects_provider_subject_hash_idx" ON "deleted_subjects" USING btree ("provider_subject_hash") WHERE "deleted_subjects"."provider_subject_hash" is not null;--> statement-breakpoint
CREATE INDEX "deleted_subjects_expires_at_idx" ON "deleted_subjects" USING btree ("expires_at");--> statement-breakpoint
ALTER TABLE "deleted_subjects" ADD CONSTRAINT "deleted_subjects_provider_subject_hash_check" CHECK ("deleted_subjects"."provider_subject_hash" is null or "deleted_subjects"."provider_subject_hash" ~ '^(apple|google|session):[A-Za-z0-9_-]{43}$');--> statement-breakpoint
ALTER TABLE "usage_counters" ADD CONSTRAINT "usage_counters_counter_check" CHECK ("usage_counters"."counter" in ('active_subscriptions', 'instances_created', 'magic_links', 'refreshes', 'anonymous_creations', 'imports', 'exports', 'mcp_calls', 'share_links', 'live_tracked', 'tracker_creations') or "usage_counters"."counter" ~ '^refresh:[A-Z0-9-]{10,40}$');--> statement-breakpoint
CREATE TABLE "sync_epoch" (
	"id" smallint PRIMARY KEY DEFAULT 1 NOT NULL,
	"epoch" bigint DEFAULT 1 NOT NULL,
	"bumped_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sync_epoch_singleton_check" CHECK ("sync_epoch"."id" = 1),
	CONSTRAINT "sync_epoch_epoch_check" CHECK ("sync_epoch"."epoch" >= 1)
);
--> statement-breakpoint
CREATE TABLE "sync_horizon" (
	"id" smallint PRIMARY KEY DEFAULT 1 NOT NULL,
	"horizon_xid" "xid8",
	"purged_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sync_horizon_singleton_check" CHECK ("sync_horizon"."id" = 1)
);
--> statement-breakpoint
INSERT INTO "sync_epoch" ("id", "epoch") VALUES (1, 1);--> statement-breakpoint
INSERT INTO "sync_horizon" ("id", "horizon_xid") VALUES (1, NULL);
