-- Generated by drizzle-kit generate --name push_to_start_token_kind (increment 11, ruling V5).
-- Widens push_tokens_kind_check with apns_live_activity_push_to_start, the ActivityKit
-- push-to-start token the app registers with POST /v1/devices. Nothing else changes; the
-- existing kinds, apns_live_activity_start included, stay valid, so no row can fail the new check.
ALTER TABLE "push_tokens" DROP CONSTRAINT "push_tokens_kind_check";--> statement-breakpoint
ALTER TABLE "push_tokens" ADD CONSTRAINT "push_tokens_kind_check" CHECK ("push_tokens"."kind" in ('apns', 'fcm', 'apns_live_activity_start', 'expo', 'apns_live_activity_push_to_start'));