-- Generated by drizzle-kit generate --name sync_purge_indexes (increment 12, ruling AA15).
-- The paged sync purge (apps/api/src/lib/sync-purge.ts) walks the oldest change rows in xid order
-- and deletes `xid < H` from both change tables in bounded steps, each well inside the app role's
-- 10 s statement_timeout. A btree on xid serves both: PostgreSQL 18 has no BRIN operator class for
-- xid8. The BRIN on created_at follows the rule for append-only tables (docs/schema-review.md
-- section 2, principle 8). Plain CREATE INDEX: the tables are small at first deploy, and the
-- migration runs in one transaction, where CONCURRENTLY is not allowed.
CREATE INDEX "user_sync_changes_xid_idx" ON "user_sync_changes" USING btree ("xid");--> statement-breakpoint
CREATE INDEX "user_sync_changes_created_at_brin_idx" ON "user_sync_changes" USING brin ("created_at");--> statement-breakpoint
CREATE INDEX "flight_sync_changes_xid_idx" ON "flight_sync_changes" USING btree ("xid");--> statement-breakpoint
CREATE INDEX "flight_sync_changes_created_at_brin_idx" ON "flight_sync_changes" USING brin ("created_at");