-- Generated by drizzle-kit generate --name ledger_calls (increment 12 re-review, ruling AB3).
-- provider_call_daily.ledger_calls: count(*) of provider_calls for the row's (day, provider) as the
-- nightly Analytics Engine rollup found it when it wrote the row. Housekeeping step 3 judges the
-- rollup's plausibility against this recorded figure, never the live count once one exists, so a
-- purge that deleted part of a day and was retried cannot find the day implausible by its own
-- shrunken count. Nullable: the ProviderBudget's own budget_daily rows never carry it, and rows
-- older than the column are judged once against the live count, which step 3 then records here.
ALTER TABLE "provider_call_daily" ADD COLUMN "ledger_calls" integer;