-- Generated by drizzle-kit generate --name push_transport (increment 14, rulings P5 and P6), plus
-- one hand-written backfill at the end. push_tokens gains app_id (the bundle or package id, the
-- APNs topic; every earlier row is the production app's, the default a registration without an
-- appId still gets), registered_at (the APNs 410 guard compares Apple's timestamp with it) and
-- permission (null until a client reports it). notification_deliveries gains one row per
-- notification and token: the unique key replaces the plain notification_id index it leads with,
-- and nothing has written the table before this increment, so no duplicate can refuse it;
-- is_test marks the admin page's test pushes, attempt_log keeps each attempt's outcome and reason.
-- The backfill sets registered_at to the time each existing row was last registered: every
-- registration before this migration wrote last_used_at, and nothing sent a push. No
-- set_updated_at trigger is recreated: neither table has a STORED generated column.
DROP INDEX "notification_deliveries_notification_id_idx";--> statement-breakpoint
ALTER TABLE "notification_deliveries" ADD COLUMN "is_test" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "notification_deliveries" ADD COLUMN "attempt_log" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "push_tokens" ADD COLUMN "app_id" text DEFAULT 'app.planeahead.mobile' NOT NULL;--> statement-breakpoint
ALTER TABLE "push_tokens" ADD COLUMN "registered_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "push_tokens" ADD COLUMN "permission" text;--> statement-breakpoint
CREATE UNIQUE INDEX "notification_deliveries_notification_id_push_token_id_key" ON "notification_deliveries" USING btree ("notification_id","push_token_id");--> statement-breakpoint
ALTER TABLE "push_tokens" ADD CONSTRAINT "push_tokens_app_id_check" CHECK (length("push_tokens"."app_id") <= 155 and "push_tokens"."app_id" ~ '^[A-Za-z0-9_-]+([.][A-Za-z0-9_-]+)+$');--> statement-breakpoint
ALTER TABLE "push_tokens" ADD CONSTRAINT "push_tokens_permission_check" CHECK ("push_tokens"."permission" is null or "push_tokens"."permission" in ('granted', 'provisional', 'denied', 'undetermined'));--> statement-breakpoint
UPDATE "push_tokens" SET "registered_at" = COALESCE("last_used_at", "created_at");