-- Generated by drizzle-kit generate --name notification_tests (increment 15, rulings N9 and N11).
-- notifications gains is_test: the notify consumer marks the rows of an injected test intent, as
-- notification_deliveries.is_test marks the admin page's test pushes. Every earlier row is a real
-- notification, the default. No set_updated_at trigger is recreated: the table has no STORED
-- generated column.
ALTER TABLE "notifications" ADD COLUMN "is_test" boolean DEFAULT false NOT NULL;