-- Generated by drizzle-kit generate --name live_tracked_released_at (increment 15, ruling Q1).
-- flight_subscriptions gains live_tracked_released_at: the persist consumer stamps it, in the
-- UPDATE that clears live_tracked when the flight is over, with the releasing instance row's own
-- Durable Object instant, and clears it wherever a slot is taken. The notify consumer pushes to a
-- subscription that is live-tracked or was released at or after the intent's producedAt. Every
-- existing row is null (no release recorded), which notify treats as not released. No
-- set_updated_at trigger is recreated: the table has no STORED generated column.
ALTER TABLE "flight_subscriptions" ADD COLUMN "live_tracked_released_at" timestamp with time zone;
