-- Generated by drizzle-kit generate --name board_calls (increment 18, ruling B10).
-- provider_calls gains the board and route_search triggers and an airport_icao column, so a
-- board or route-search call is attributed to its airport. Generated first as 0009 on this branch,
-- then regenerated as 0010 after increment 15's 0009 (live_tracked_released_at) was merged in.
ALTER TABLE "provider_calls" DROP CONSTRAINT "provider_calls_trigger_check";--> statement-breakpoint
ALTER TABLE "provider_calls" ADD COLUMN "airport_icao" text;--> statement-breakpoint
ALTER TABLE "provider_calls" ADD CONSTRAINT "provider_calls_airport_icao_check" CHECK ("provider_calls"."airport_icao" is null or "provider_calls"."airport_icao" ~ '^[A-Z0-9]{4}$');--> statement-breakpoint
ALTER TABLE "provider_calls" ADD CONSTRAINT "provider_calls_trigger_check" CHECK ("provider_calls"."trigger" in ('alarm', 'provider_alert', 'adb_alert', 'user_search', 'user_refresh', 'reconcile', 'backfill', 'cron', 'import', 'manual', 'board', 'route_search'));