-- Generated by drizzle-kit generate --name route_searches (increment 18, rulings B9 and B10).
-- usage_counters accepts the route_searches counter: route searches per user, and per salted IP
-- for an anonymous account, per UTC day. The check is dropped and re-added as 0003 did; no row
-- changes, and every counter the old check accepted is still accepted.
ALTER TABLE "usage_counters" DROP CONSTRAINT "usage_counters_counter_check";--> statement-breakpoint
ALTER TABLE "usage_counters" ADD CONSTRAINT "usage_counters_counter_check" CHECK ("usage_counters"."counter" in ('active_subscriptions', 'instances_created', 'magic_links', 'refreshes', 'anonymous_creations', 'imports', 'exports', 'mcp_calls', 'share_links', 'live_tracked', 'tracker_creations', 'route_searches') or "usage_counters"."counter" ~ '^refresh:[A-Z0-9-]{10,40}$');