/**
 * The Worker's environment and the per-request variables.
 *
 * `Cloudflare.Env` is generated by `wrangler types` into `worker-configuration.d.ts` from
 * wrangler.jsonc, and that file is committed so CI and editors agree without running wrangler.
 * Regenerate it with `pnpm --filter @planeahead/api run cf-typegen` after any binding change.
 *
 * Secrets are declared here as well as generated. `wrangler types` reads the `secrets.required`
 * blocks since increment 8 (and `.dev.vars`, which is gitignored), and the committed file was
 * regenerated in increment 12 with them; this interface stays the documented source, and every
 * secret is optional in it: a Worker that is missing one must fail with its own message, not with
 * a type error that never runs.
 */

import type { EnvironmentName } from '@planeahead/shared';
import type { AuthRuntime } from './auth/runtime';
import type { AuthenticatedUser } from './auth/user';
import type { AccessIdentity } from './middleware/access';
import type { IdempotencyContext } from './middleware/idempotency';

/**
 * Secrets set with `wrangler secret put` (staging and production) or `.dev.vars` (local), and
 * under test by `.dev.vars.test` through vitest.config.ts. See `.dev.vars.example`.
 *
 * Every name here is also listed in `.dev.vars.example`, and `test/workers/secrets-in-logs.test.ts`
 * asserts that none of their VALUES ever reaches a log line.
 */
export interface WorkerSecrets {
  /** Sentry DSN. Unset means the SDK initialises with no transport and drops every event. */
  readonly SENTRY_DSN?: string;

  /**
   * Better Auth's signing secret for session cookies. At least 32 characters; `createAuth`
   * refuses to start without it, because Better Auth itself would fall back to a public default
   * (it keys that check on NODE_ENV, which Workers never set).
   */
  readonly BETTER_AUTH_SECRET?: string;

  /**
   * Key-encryption keys for the envelope module, one per version, standard padded base64 of 32
   * bytes. The highest configured version is the one new data-encryption keys are wrapped under;
   * older versions stay configured until every `user_keys` row has been re-wrapped
   * (`docs/security/threat-model.md`, KEK rotation). Three are declared for the type; the key
   * provider reads `TOKEN_KEK_V1` through `TOKEN_KEK_V32` dynamically (`readKekSecrets`).
   */
  readonly TOKEN_KEK_V1?: string;
  readonly TOKEN_KEK_V2?: string;
  readonly TOKEN_KEK_V3?: string;

  /** Sign in with Apple private key (`.p8`), PKCS8 PEM with the newlines written as `\n`. */
  readonly APPLE_SIWA_P8?: string;
  /** Key id of that `.p8`, from Certificates, Identifiers and Profiles. */
  readonly APPLE_SIWA_KEY_ID?: string;
  /** Apple Developer team id: the `iss` of the client secret. */
  readonly APPLE_SIWA_TEAM_ID?: string;
  /** The iOS bundle id: `aud` of native identity tokens and `client_id` at the token endpoint. */
  readonly APPLE_BUNDLE_ID?: string;

  /** The three Google OAuth client ids a native identity token may name as `aud`. */
  readonly GOOGLE_CLIENT_ID_WEB?: string;
  readonly GOOGLE_CLIENT_ID_IOS?: string;
  readonly GOOGLE_CLIENT_ID_ANDROID?: string;

  /** Resend API key. Unset means magic-link mail goes to the logging `NoopSender`. */
  readonly RESEND_API_KEY?: string;

  /** AeroDataBox direct-gateway key (`X-Api-Key`), the primary flight data provider (increment 6). */
  readonly AERODATABOX_API_KEY?: string;
  /** FlightAware AeroAPI key (`x-apikey`). Unused while `AEROAPI_MODE` is `mock`. */
  readonly AEROAPI_API_KEY?: string;

  /**
   * 256-bit path tokens for the webhook receivers, one per provider and per environment:
   * `/v1/webhooks/aerodatabox/{token}` and `/v1/webhooks/aeroapi/{token}`. Neither provider signs
   * its deliveries (AeroDataBox subscriptions carry no secret and must not require
   * authorisation), so the unguessable path is the authentication. 43 base64url characters
   * (`openssl rand -base64 32 | tr '+/' '-_' | tr -d '=')`) or 64 hex characters.
   */
  readonly WEBHOOK_TOKEN_AERODATABOX?: string;
  readonly WEBHOOK_TOKEN_AEROAPI?: string;

  /**
   * HMAC-SHA-256 key for `deleted_subjects.provider_subject_hash` (increment 8, ruling K8): the
   * Apple and Google subjects and the session tokens of a deleted account are stored only as a
   * keyed hash under this secret, which never enters the database. At least 32 characters
   * (`openssl rand -base64 32`). Missing means `POST /v1/me/delete` refuses (500) before it
   * touches anything, and a dead session is answered `unauthenticated` rather than
   * `account_deleted`.
   */
  readonly DELETED_SUBJECT_HMAC_KEY?: string;

  /**
   * Root of the daily salt for anonymous per-IP caps (increment 8, ruling K2): the salt for a UTC
   * day is HMAC-SHA-256(secret, day), and the counter subject is base64url
   * HMAC-SHA-256(salt, CF-Connecting-IP), so `usage_counters` never holds an address and
   * yesterday's subjects cannot be recomputed from today's. At least 32 characters.
   */
  readonly IP_SALT_SECRET?: string;

  /**
   * Cloudflare API token for the operational surface (increment 12), OPTIONAL: Account > Account
   * Analytics > Read (the Analytics Engine SQL API: the nightly provider-call rollup and the admin
   * page's figures for today) and Account > Queues > Read (the admin page's queue depths), with
   * `CF_ACCOUNT_ID` (a var). Unset means the rollup records a skipped run and the admin page shows
   * those figures as unavailable; nothing else depends on it, so it is not in
   * `WORKER_SECRET_NAMES` (which wrangler requires before a first deploy) but in
   * `OPTIONAL_SECRET_NAMES`.
   */
  readonly CF_API_TOKEN?: string;

  /**
   * The push transport's credentials (increment 14, ruling P7): REQUIRED in production (its
   * `secrets.required`), OPTIONAL in staging and locally, so staging deploys before the Apple
   * account exists. Without the three APNs names the `push` consumer holds APNs jobs as
   * `not_configured`, without the service account it holds FCM jobs the same way, and the admin
   * page says so. `PUSH_SECRET_NAMES` below lists them.
   *
   * `APNS_KEY_P8`: the APNs auth key (`.p8`), PKCS8 PEM with the newlines written as `\n`, like
   * `APPLE_SIWA_P8`. One key per environment (plan section 3): a team-scoped Sandbox key on staging,
   * a Production key on production. `APNS_KEY_ID`: its 10-character key id. `APNS_TEAM_ID`: the
   * 10-character team id, the JWT's `iss`.
   */
  readonly APNS_KEY_P8?: string;
  readonly APNS_KEY_ID?: string;
  readonly APNS_TEAM_ID?: string;
  /**
   * The FCM HTTP v1 service account as its JSON key file (`type`, `project_id`, `private_key_id`,
   * `private_key`, `client_email`): the project id names the send endpoint, the key signs the RS256
   * assertion exchanged for an access token. A dedicated account holding only
   * `cloudmessaging.messages.create` (R1 F39).
   */
  readonly FCM_SERVICE_ACCOUNT_JSON?: string;

  /**
   * Test seams. Unset in every deployed environment, where the code falls back to the real
   * hosts; the Workers suite points them at `test/fake-providers.ts`.
   */
  readonly APPLE_JWKS_URL?: string;
  readonly APPLE_TOKEN_URL?: string;
  /** Apple's `/auth/revoke` (increment 8); the suite points it at the fake provider server. */
  readonly APPLE_REVOKE_URL?: string;
  readonly GOOGLE_JWKS_URL?: string;
  readonly RESEND_API_URL?: string;
}

/**
 * The secret names as a runtime value, in the same order as the interface above. Kept beside the
 * type so a test can assert that every one is listed in `.dev.vars.example` and `.dev.vars.test`
 * (ruling F5) and that none of their values reaches a log line. The test seams below are not
 * secrets and are not in this list.
 */
export const WORKER_SECRET_NAMES = [
  'SENTRY_DSN',
  'BETTER_AUTH_SECRET',
  'TOKEN_KEK_V1',
  'APPLE_SIWA_P8',
  'APPLE_SIWA_KEY_ID',
  'APPLE_SIWA_TEAM_ID',
  'APPLE_BUNDLE_ID',
  'GOOGLE_CLIENT_ID_WEB',
  'GOOGLE_CLIENT_ID_IOS',
  'GOOGLE_CLIENT_ID_ANDROID',
  'RESEND_API_KEY',
  'AERODATABOX_API_KEY',
  'AEROAPI_API_KEY',
  'WEBHOOK_TOKEN_AERODATABOX',
  'WEBHOOK_TOKEN_AEROAPI',
  'DELETED_SUBJECT_HMAC_KEY',
  'IP_SALT_SECRET',
] as const satisfies readonly (keyof WorkerSecrets)[];

/**
 * Secrets the Worker reads when present and does without otherwise (increment 12). Listed in
 * `.dev.vars.example` like the required ones; never in `secrets.required`.
 */
export const OPTIONAL_SECRET_NAMES = [
  'CF_API_TOKEN',
] as const satisfies readonly (keyof WorkerSecrets)[];

/**
 * The push transport's credentials (increment 14, ruling P7): in production's `secrets.required`
 * after `WORKER_SECRET_NAMES`, in no other environment's. Listed in `.dev.vars.example`, given a
 * dummy in `.dev.vars.test`, and covered by the secrets-in-logs test like the required names.
 */
export const PUSH_SECRET_NAMES = [
  'APNS_KEY_P8',
  'APNS_KEY_ID',
  'APNS_TEAM_ID',
  'FCM_SERVICE_ACCOUNT_JSON',
] as const satisfies readonly (keyof WorkerSecrets)[];

/** Bindings that redirect an external endpoint at a test double. Never set in a deployment. */
export const TEST_SEAM_NAMES = [
  'APPLE_JWKS_URL',
  'APPLE_TOKEN_URL',
  'APPLE_REVOKE_URL',
  'GOOGLE_JWKS_URL',
  'RESEND_API_URL',
] as const satisfies readonly (keyof WorkerSecrets)[];

/**
 * Provider settings (increment 6). Not secrets, but not in wrangler.jsonc `vars` either: each
 * has a cautious default in code (`src/providers/config.ts`), so a deployment that sets none of
 * them runs AeroAPI in `mock` mode, on the AeroDataBox Starter limits, with AeroDataBox alerts
 * off. Set them in `.dev.vars` locally and with `wrangler secret put` (or a `vars` entry) in a
 * deployment that needs a non-default.
 */
export interface WorkerSettings {
  /** `mock` (default) routes every cadence window to AeroDataBox; `live` enables AeroAPI. */
  readonly AEROAPI_MODE?: string;
  /** `starter` (default), `growth` or `scale`: per-second limit, lookahead, FIDS window. */
  readonly ADB_PLAN?: string;
  /** `true` enables the AeroDataBox webhook receiver; anything else answers 404. */
  readonly ADB_ALERTS_ENABLED?: string;
  /**
   * Test seam (increment 7): the AeroDataBox base URL the router hands the adapter. Unset in
   * every deployed environment, where the adapter's own `https://api.aerodatabox.com/` applies;
   * the Workers suite points it at `test/fake-providers.ts` (`TEST_FAKE_PROVIDERS_ORIGIN` plus
   * `/aerodatabox`), so a FlightTracker alarm in a test fetches scripted fixtures over HTTP
   * through the real adapter and the real router.
   */
  readonly AERODATABOX_BASE_URL?: string;
  /**
   * Test seam (increment 7): `true` lets the FlightTracker and DesignatorResolver `_setClock`
   * RPC replace the clock every decision reads. Set ONLY by test/globalSetup.ts, never in
   * wrangler.jsonc or `.dev.vars`; with it unset the RPC throws and the objects read `Date.now()`.
   */
  readonly TEST_CLOCK?: string;
  /**
   * `true` makes `POST /v1/me/delete` call RevenueCat's `DELETE /v1/subscribers/{id}` (increment
   * 8). Off in Phase 0, where the call is a typed stub (src/billing/revenuecat.ts) that records
   * what it would have done: RevenueCat deletion is optional and does not cancel a store
   * subscription.
   */
  readonly REVENUECAT_DELETE_ENABLED?: string;
  /**
   * The bundle ids a native Apple identity token may name as `aud`, comma separated (increment
   * 12). Unset means the environment's variants as the association files name them
   * (`BUNDLE_IDS_BY_ENVIRONMENT`: production and preview against production, the development
   * build against staging), plus `APPLE_BUNDLE_ID`.
   */
  readonly APPLE_BUNDLE_IDS?: string;
  /**
   * The user ids whose tokens the admin page's "Send a test push" may target in production,
   * comma separated (increment 14, ruling P8; the plan's event injector reads the same list in
   * increment 15). Unset or empty in production means nobody's: the action refuses every token.
   * Staging and local ignore it. Not a secret, but kept out of wrangler.jsonc: set it with
   * `wrangler secret put` (or a `vars` entry) in production only.
   */
  readonly PUSH_INJECT_ALLOWED_USER_IDS?: string;
}

export const WORKER_SETTING_NAMES = [
  'AEROAPI_MODE',
  'ADB_PLAN',
  'ADB_ALERTS_ENABLED',
  'REVENUECAT_DELETE_ENABLED',
  'APPLE_BUNDLE_IDS',
  'PUSH_INJECT_ALLOWED_USER_IDS',
] as const satisfies readonly (keyof WorkerSettings)[];

export type Env = Cloudflare.Env & WorkerSecrets & WorkerSettings;

/** Values middleware puts on the context for later middleware and route handlers to read. */
export interface Variables {
  /** Correlation id for this request. Echoed in the response and on every log line. */
  requestId: string;
  /**
   * The caller, or null when the request is unauthenticated. Set by the auth middleware from
   * the Better Auth session; `undefined` in every slot ahead of it (read it as `?? null`).
   */
  user: AuthenticatedUser | null;
  /**
   * The request's database handle, Better Auth instance, envelope and mail sender, created on
   * first use by `authRuntime(c)` (src/auth/runtime.ts) and shared by the auth middleware and
   * the routes so one request opens one client. Unset until something asks for it.
   */
  authRuntime: AuthRuntime | undefined;
  /**
   * Set by the auth middleware when the request presented a session cookie that no longer
   * resolves AND whose token belongs to a deleted account (`deleted_subjects`), so `requireUser`
   * answers 401 `account_deleted` (wipe the local store) instead of `unauthenticated` (sign in
   * again). Unset otherwise.
   */
  accountDeleted: boolean | undefined;
  /**
   * Set by the auth middleware when the session it resolved was read from the `sessions` row (a
   * mutating request, the search's canonical path, or a cached cookie the tombstone check could
   * not vouch for), so `requireFreshSession()` need not read it again. Unset when the session came
   * from the cookie cache or none was resolved.
   */
  sessionFromRow: boolean | undefined;
  /**
   * Set by the `/v1` idempotency instance for a keyed mutating request: the key, its scope and its
   * store, which `idempotencyGate()` reserves against once the route has validated the body.
   */
  idempotency: IdempotencyContext | undefined;
  /**
   * Set by the Cloudflare Access middleware on `/admin` (increment 12) once the
   * `Cf-Access-Jwt-Assertion` verified: the Access subject and email. Unset everywhere else.
   */
  accessIdentity: AccessIdentity | undefined;
}

/**
 * The Hono generic for this app. Variables are declared per app, never through the global
 * `ContextVariableMap`: the global map would type `c.var.user` as present on routes where the
 * auth middleware never ran.
 */
export interface AppBindings {
  Bindings: Env;
  Variables: Variables;
}

/**
 * Deployment environment name, from the `ENVIRONMENT` var in wrangler.jsonc. Defined in
 * `@planeahead/shared` because `GET /health` answers it and the typed client may import only
 * leaf types from there.
 */
export type { EnvironmentName };

export function environmentName(env: Env): EnvironmentName {
  const value: string = env.ENVIRONMENT;
  if (value === 'local' || value === 'test' || value === 'staging' || value === 'production') {
    return value;
  }
  return 'local';
}

/**
 * Whether this deployment serves the airport boards and the route search (increment 18, R8):
 * `BOARDS_ENABLED` from wrangler.jsonc `vars`, `"true"` in local and staging, `"false"` in
 * production until AeroDataBox confirms in writing that boards are End Use and the per-user board
 * budget (R3) exists. Read through a widened string, like `ENVIRONMENT` above: `wrangler types`
 * knows only the literals the config declares, and any value but exactly `"true"` (absent, a
 * dashboard override, `TRUE` or ` true ` included) is off (the re-review's N6).
 */
export function boardsEnabled(env: Pick<Env, 'BOARDS_ENABLED'>): boolean {
  const value: string | undefined = env.BOARDS_ENABLED;
  return value === 'true';
}
