/**
 * The Worker's environment and the per-request variables.
 *
 * `Cloudflare.Env` is generated by `wrangler types` into `worker-configuration.d.ts` from
 * wrangler.jsonc, and that file is committed so CI and editors agree without running wrangler.
 * Regenerate it with `pnpm --filter @planeahead/api run cf-typegen` after any binding change.
 *
 * Secrets are declared here rather than generated. `wrangler types` reads `.dev.vars` for secret
 * names, `.dev.vars` is gitignored, and a generated type that depends on an untracked file drifts
 * between a developer's machine and CI. Every secret is optional in the type: a Worker that is
 * missing one must fail with its own message, not with a type error that never runs.
 */

import type { AuthenticatedUser } from './auth/user';

/**
 * Secrets set with `wrangler secret put` (staging and production) or `.dev.vars` (local).
 * See `.dev.vars.example` for the local template.
 */
export interface WorkerSecrets {
  /** Sentry DSN. Unset means the SDK initialises with no transport and drops every event. */
  readonly SENTRY_DSN?: string;
}

export type Env = Cloudflare.Env & WorkerSecrets;

/** Values middleware puts on the context for later middleware and route handlers to read. */
export interface Variables {
  /** Correlation id for this request. Echoed in the response and on every log line. */
  requestId: string;
  /**
   * The caller, or null when the request is unauthenticated. The increment 4 middleware always
   * sets null; increment 5 resolves a Better Auth session here.
   */
  user: AuthenticatedUser | null;
}

/**
 * The Hono generic for this app. Variables are declared per app, never through the global
 * `ContextVariableMap`: the global map would type `c.var.user` as present on routes where the
 * auth middleware never ran.
 */
export interface AppBindings {
  Bindings: Env;
  Variables: Variables;
}

/** Deployment environment name, from the `ENVIRONMENT` var in wrangler.jsonc. */
export type EnvironmentName = 'local' | 'test' | 'staging' | 'production';

export function environmentName(env: Env): EnvironmentName {
  const value: string = env.ENVIRONMENT;
  if (value === 'local' || value === 'test' || value === 'staging' || value === 'production') {
    return value;
  }
  return 'local';
}
