/**
 * Adds the Wear OS shell to the generated Android project (increment 11, ADR 0008). Written from
 * scratch: Expo has no Wear OS support of any kind (facts section 5).
 *
 * What it does on every `expo prebuild`:
 * - `settings.gradle` gets `include ':wear'`;
 * - `android/wear/build.gradle` is generated: a `com.android.application` module with Compose for
 *   Wear OS and one Tile, whose sources stay in the repository at apps/mobile/wear/src/main (the
 *   build script points its source sets there, so `android/` remains pure build output).
 *
 * Compile only: `./gradlew assembleDebug` builds the watch APK next to the phone app's, and EAS
 * builds, which run `:app:` tasks, never touch it. The watch app shares the phone app's package
 * name (`applicationId`), which is what pairs the two on a device.
 *
 * Every library version is pinned here, chosen against what Expo SDK 57 builds with (React
 * Native 0.86.3: Kotlin 2.1.20, Android Gradle Plugin 8.12.0, compileSdk and targetSdk 36; ADR
 * 0008 records the choice). The newest Wear Compose, 1.7.0, needs compileSdk 37 and AGP 9.1, so
 * the 1.6 line is the one this toolchain can build.
 */

import { withDangerousMod, withSettingsGradle, type ConfigPlugin } from 'expo/config-plugins';

/** The artefacts and versions the Wear module compiles against (Google Maven, 2026-09-23). */
export const WEAR_DEPENDENCIES = {
  'androidx.wear.compose:compose-material3': '1.6.2',
  'androidx.wear.compose:compose-foundation': '1.6.2',
  'androidx.compose.ui:ui': '1.9.0',
  'androidx.compose.foundation:foundation-layout': '1.9.0',
  'androidx.activity:activity-compose': '1.11.0',
  'androidx.wear.tiles:tiles': '1.6.2',
  'androidx.wear.protolayout:protolayout': '1.4.2',
  'androidx.concurrent:concurrent-futures': '1.3.0',
  'com.google.guava:listenablefuture': '1.0',
} as const;

/** Wear OS 3, the first version with Tiles and Compose for Wear OS as the platform path. */
export const WEAR_MIN_SDK = 30;

export const WEAR_PROJECT = ':wear';

export interface WearBuildOptions {
  /** The phone app's package; the watch app must share it to pair. */
  readonly applicationId: string;
  readonly versionName: string;
}

/** Appends `include ':wear'` to settings.gradle once. */
export function includeWearProject(settingsGradle: string): string {
  if (settingsGradle.includes(`include '${WEAR_PROJECT}'`)) {
    return settingsGradle;
  }
  const comment = '// plugins/withWearApp.ts: the Wear OS shell (ADR 0008)';
  return `${settingsGradle.trimEnd()}\n\n${comment}\ninclude '${WEAR_PROJECT}'\n`;
}

/** The generated android/wear/build.gradle. */
export function wearBuildGradle({ applicationId, versionName }: WearBuildOptions): string {
  const dependencies = Object.entries(WEAR_DEPENDENCIES)
    .map(([artefact, version]) => `  implementation '${artefact}:${version}'`)
    .join('\n');
  return `// Generated by apps/mobile/plugins/withWearApp.ts on every expo prebuild: edit the plugin, not
// this file. The Wear OS shell (ADR 0008), compile only; its sources are apps/mobile/wear/src/main.
buildscript {
  repositories {
    google()
    mavenCentral()
  }
  dependencies {
    // The Compose compiler ships with Kotlin, so it takes the version the root project resolved.
    classpath("org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin:\${rootProject.ext.kotlinVersion}")
  }
}

apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

def wearSources = new File(rootProject.projectDir, '../wear/src/main')

android {
  namespace 'app.planeahead.wear'
  compileSdk rootProject.ext.compileSdkVersion

  defaultConfig {
    applicationId '${applicationId}'
    minSdk ${WEAR_MIN_SDK}
    targetSdk rootProject.ext.targetSdkVersion
    versionCode 1
    versionName '${versionName}'
  }

  sourceSets {
    main {
      manifest.srcFile new File(wearSources, 'AndroidManifest.xml')
      java.srcDirs = [new File(wearSources, 'java')]
      res.srcDirs = [new File(wearSources, 'res')]
    }
  }

  buildFeatures {
    compose true
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
  compilerOptions {
    jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
  }
}

dependencies {
${dependencies}
}
`;
}

/** Node's fs and path, typed here: the app's tsconfig loads no Node types (app.config.ts too). */
interface NodeFs {
  mkdirSync(path: string, options: { recursive: true }): void;
  writeFileSync(path: string, contents: string): void;
}
interface NodePath {
  join(...parts: string[]): string;
}
declare const require: (id: 'fs' | 'path') => unknown;

export const withWearApp: ConfigPlugin = (config) => {
  const applicationId = config.android?.package;
  if (applicationId === undefined) {
    throw new Error('withWearApp: android.package must be set before this plugin runs');
  }
  const versionName = config.version ?? '0.0.0';

  const withSettings = withSettingsGradle(config, (mod) => {
    mod.modResults.contents = includeWearProject(mod.modResults.contents);
    return mod;
  });

  return withDangerousMod(withSettings, [
    'android',
    (mod) => {
      const fs = require('fs') as NodeFs;
      const path = require('path') as NodePath;
      const moduleDir = path.join(mod.modRequest.platformProjectRoot, 'wear');
      fs.mkdirSync(moduleDir, { recursive: true });
      fs.writeFileSync(
        path.join(moduleDir, 'build.gradle'),
        wearBuildGradle({ applicationId, versionName }),
      );
      return Promise.resolve(mod);
    },
  ]);
};

export default withWearApp;
